### ISSUE TITLE
Dataset DOI Not Reserved

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#32]
Quite a few time, we have experienced that the DOI chosen by DataverseNO for a newly created dataset could not been reserved at DataCite. The following warning is displayed:

> Dataset DOI Not Reserved – The DOI displayed in the citation for this dataset has not yet been reserved with DataCite. Please do not share this DOI until it has been reserved.

The latest incident happened today, December 1, 2022, between 10:40 and 10:50 CET.

According to the DataCite Status Page ([https://status.datacite.org/](https://status.datacite.org/)), all their services were operational at that time.

Please check the DataverseNO log file for possible clues about what is going wrong in these cases.

**Comment by Louis-wr** [comment]
Dataverse.no could not communicate for a few minutes with DataCite. Given the 503 error it would seams the issue is indeed with Datacite.

`[2022-12-01T10:45:37.934+0100] [Payara 5.2021.6] [WARNING] [] [edu.harvard.iq.dataverse.DOIDataCiteServiceBean] [tid: _ThreadID=107 _ThreadName=http-thread-pool::jk-connector(3)] [timeMillis: 1669887937934] [levelValue: 900] [[
  Identifier not created: create failed
java.io.IOException: Response from postMetadata: 503, <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>
`

**Comment by philippconzett** [comment]
DataCite had problems with their services; cf. email notification "MDS experiencing timeouts and slowness". The problem is resolved now, and I was able to publish a new dataset draft.
